# Generated by Django 5.0 on 2025-11-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS_Catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen_url',
            field=models.CharField(blank=True, default='default_book.png', max_length=500, null=True),
        ),
    ]
