# Generated by Django 5.0 on 2025-12-01 20:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MS_Catalogo', '0002_alter_libro_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lector_id', models.IntegerField(verbose_name='ID del Lector')),
                ('fecha_prestamo', models.DateField(auto_now_add=True, verbose_name='Fecha de Préstamo')),
                ('fecha_devolucion_esperada', models.DateField(default=datetime.date(2025, 12, 8), verbose_name='Devolución Esperada')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Préstamo Activo')),
                ('libro', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='MS_Catalogo.libro', verbose_name='Libro Prestado')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
