# Generated by Django 5.0 on 2025-12-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lector_id', models.IntegerField()),
                ('libro_id', models.IntegerField()),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('listo', 'Listo para retirar'), ('rechazado', 'Rechazado'), ('prestado', 'Prestado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
        ),
    ]
